set -g default-terminal "screen-256color"

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Remap prefix to Ctrl-a
unbind-key C-b
set-option -g prefix C-a
bind-key C-a send-prefix
# Allow Ctrl to be held for key presses after prefix
bind-key -r ^N next-window
bind-key -r ^P previous-window

set -g focus-events on

setw -g mode-keys vi

source ~/.config/tmux/tmux-gruvbox.conf
